#使用问题联系qq2260483272
#同时接中小型插件定制

#如已购买插件，联系qq获取cdk
cdk: ''
pokemon-index-count: 718
setting:
  ans-reg: '^(.*)@pkm@(.*)$'
  chat-start: 'wi'
  #公告间隔
  bro-time: 20
  #公布正确答案时间
  ans-bro: 2
  #开启竞猜时间
  time:
    schedule:
      #周五的9点到凌晨三点 每90分钟进行一次
      5: '3:0:0,15:0:0,90'
      #周五以外的其他时间 0点至23点 每5分钟的间隔开启一次游戏
      other: '0:0:0,23:0:0,5'
rewards:
  STONE:
    #概率(权重)
    chance: 10
    cmds:
      - 'give @p@ stone 1'
  GRASS:
    #概率(权重)
    chance: 20
    cmds:
      - 'give @p@ grass 1'